# Generated by Django 3.2.3 on 2021-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post', 'post'), ('comment', 'comment'), ('follow', 'follow')], max_length=20),
        ),
    ]
