version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7
      - image: postgres:10-alpine
        environment:
          POSTGRES_DB: app
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: build
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: test
          command: |
            . venv/bin/activate
            python3 manage.py test
workflows:
  version: 2
  test:
    jobs:
      - build